### ISSUE TITLE
Service "oro_security.error_listener": Parent definition "exception_listener" does not exist. 

### ISSUE THREAD

**Issue by hvanoch** [oroinc/platform#1056]
**Summary**  
Trying to upgrade to 4.2.1 but receiving the error:  Service "oro_security.error_listener": Parent definition "exception_listener" does not exist. 

**Steps to reproduce**  
upgrade to 4.2.1. Run cache clear.

**Actual Result**
Exception thrown:
Service "oro_security.error_listener": Parent definition "exception_listener" does not exist. 

**Expected Result**  
Cache is cleared

**Details about your environment**
- OroPlatform version: 4.2.1
- PHP version: 7.4
- Database  version MySQl 8.0

**Additional information**  
service "exception_listener is defined in `vendor/symfony/framework-bundle/Resources/config/web.xml:98 `
But it is removed by symfony again in `vendor/symfony/twig-bundle/DependencyInjection/Compiler/ExceptionListenerPass.php:43`

**Comment by anyt** [comment]
Make sure you correctly upgraded the application https://doc.oroinc.com/backend/setup/upgrade-to-new-version/.
The error happens because your `config/config.yml` is not in sync with the one provided in the 4.2.1 version of the Oro application. To be specific, this change is missing https://github.com/oroinc/platform-application/commit/e6dff926528213d6044afff15ccb99daedc0fda1#diff-cb047af3dd43afd8e756ef9289e96ce3139a3f7e5fba09e05d8859953257587cL41.

**Comment by hvanoch** [comment]
Thank you. I noticed the change in `config/config.yml`. But for some reason I had also set that option in the `config/config_dev.yml` 
After removing it worked!
