### ISSUE TITLE
Bug:  Dashboard with "business_sales_channel_statistics" throws an exception in 2.1

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#675]
Hi Oro Team,

The widget was removed or renamed in 2.1,  when a dashboard is rendered with that widget, an exception is thrown. Which is sad when this is the main dashboard ! 😢 

```
    "class": "Twig_Error_Runtime",
    "message": "An exception has been thrown during the rendering of a template (\"Can't find configuration for: business_sales_channel_statistics\").",
    "code": 0,
    "file": "vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Resources/views/Index/default.html.twig:118",

.....

  "previous": {
        "class": "Oro\\Bundle\\DashboardBundle\\Exception\\InvalidConfigurationException",
        "message": "Can't find configuration for: business_sales_channel_statistics",
        "code": 0,
        "file": "vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/ConfigProvider.php:115",
        "trace": [
            "vendor/oro/platform/src/Oro/Bundle/DashboardBundle/Model/WidgetConfigs.php:178",
```

Have a good day,
Samuel

**Comment by sadortun** [comment]
I am not sure if the source of this issue is a problem in CRM migrations. In any case, platform dashboard should be able to handle this gracefully.

**Comment by mkudelya** [comment]
Hi @sadortun 

You are right, the Business Sales Channel Statistic widget has been deleted and broken down into two widgets: Lead Statistics and Opportunity Statistics.
Unfortunately, the issue appears when the system contains more than one 'business_sales_channel_statistics' widget in oro_dashboard_widget table. Only the first record will be broken into two: lead_statistics and opportunity_statistics. As a workaround, I suggest you create two widgets instead of the business_sales_channel_statistics on each dashboard manually in the oro_dashboard_widget table.

**Comment by mkudelya** [comment]
Internal bug CRM-8126

**Comment by sadortun** [comment]
Thanks. I, ce already deleted thé widget and re-added them !
