### ISSUE TITLE
API Unable to search accounts by name, if contain a coma

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#791]
Hi Oro Team,

Tested with demo.orocrm.com

When you have an account that contains a coma `,` in the name, we are unable to find it using the JSON API

![image](https://user-images.githubusercontent.com/794449/34740048-269cba2a-f54c-11e7-8ce2-e95a45aa6f32.png)

I've also tried to use escape characters, but no luck. Do you have an idea on how to solve this issue ?

![image](https://user-images.githubusercontent.com/794449/34740003-0b6fa186-f54c-11e7-8d53-eb07382bede6.png)

Search with the filter is working:

![image](https://user-images.githubusercontent.com/794449/34740064-364bf4ae-f54c-11e7-975d-4d0c156fa886.png)

Thanks,
Samuel

**Comment by aalgogiver** [comment]
Hi, @sadortun.
Thanks for reporting.
As a quick fix consider to set `allow_array:false` for the filter.

**Comment by manowark** [comment]
INTERNAL ID: BAP-16336

**Comment by vsoroka** [comment]
To fix this issue we have changed the default value of `allow_array` option from `true` to `false` for all string filters.
The fix will be available since version 2.6.

Actually a comma in string filters is quite complex issue because we cannot simply request REST API clients to escape a comma, because it is not covered by JSON.API specification and it may do our API incompatible with existing JSON.API clients.
This is the reason why we decided to disable filtering by several values for string fields.
In a future we are going to implement a complex filtering (e.g. similar to [OData filters](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Ref356810738)) that will solve this issue.  

Also here is an interesting discussion about a comma in string filters https://github.com/json-api/json-api/issues/69.
