### ISSUE TITLE
Multiple roles issue.

### ISSUE THREAD

**Issue by xgitxhubx** [oroinc/platform#794]
I think there is an issue with multiple roles.

Step to reproduce on demo:
1. Login to admin and edit "Buyer" role: on "Order" entity, change "View" to "Department".
![buyer-role](https://user-images.githubusercontent.com/30398975/35140229-0c308bdc-fd29-11e7-93f4-53c4928b5878.png)

2. Add new role "Test": on "Order" entity, change "View" to "Corporate".
![test-role](https://user-images.githubusercontent.com/30398975/35140234-1163c416-fd29-11e7-933b-b43810a8e88b.png)

3. So we have all roles:
![all-roles](https://user-images.githubusercontent.com/30398975/35140253-22f9a236-fd29-11e7-86ab-a3020875befc.png)

4. Edit roles of "Branda": "Buyer" + "Test":
![add-roles](https://user-images.githubusercontent.com/30398975/35140288-3d037a12-fd29-11e7-9269-b9747ad5be47.png)

5. Login with "Branda" and go to "Order":
![actually](https://user-images.githubusercontent.com/30398975/35140306-4b4ac12a-fd29-11e7-9480-f083ce1b5eba.png)

6. Remove "Buyer" role of "Branda":
![edit-roles](https://user-images.githubusercontent.com/30398975/35140322-5eb9a262-fd29-11e7-8378-c98770779272.png)

7. Login with "Branda" and go to "Order":
![expectation](https://user-images.githubusercontent.com/30398975/35140357-831fcbcc-fd29-11e7-9daf-bbfd4b21074e.png)

The results of step 5 (roles: "Buyer" + "Test") and step 7 (roles: "Test") are different. The expectation is the results of step 5 equal to step 7, but actually, step 5 totals less than step 7.
The code to determine the permissions: https://github.com/oroinc/customer-portal/blob/master/src/Oro/Bundle/CustomerBundle/Security/CustomerUserProvider.php#L195

Another question:
https://github.com/oroinc/customer-portal/blob/master/src/Oro/Bundle/CustomerBundle/EventListener/Datagrid/CustomerDatagridListener.php#L96
Should we check permissions for deep/system before local? ie:
```
        if ($this->permissionShowAllCustomerItemsForChild()) {
            $this->showAllCustomerItems($config, true);
        }
        elseif ($this->permissionShowAllCustomerItems()) {
            $this->showAllCustomerItems($config);
        }
```

**Comment by br0ther** [comment]
Hi @xgitxhubx!
Thanks for the question. 
Tried to reproduce your steps two times :) But after step 4

> 'Edit roles of "Branda": "Buyer" + "Test":''

after logging under  "Branda" I'm always getting exactly **45** Total Orders. So its equal to orders taken with Test only role. So all works fine. Please recheck your STR again to reproduce this issue

**Comment by xgitxhubx** [comment]
Hi @br0ther ,

I also recheck 2 times again.
Please take a look at my recorded video:

[Cinnamon-Jan-23-2018_10:02:38am.mkv.zip](https://github.com/oroinc/platform/files/1654384/Cinnamon-Jan-23-2018_10.02.38am.mkv.zip)

**Comment by manowark** [comment]
Hello, @xgitxhubx.

Just double checked your steps to reproduce.
One difference - I tested on last master, because recently we fixed bug with displaying data on frontend grids depend on user permissions.

This is related commits:
https://github.com/oroinc/customer-portal/commit/b9080a771d121c0360e6c0b1230acb2bbc22d089
https://github.com/oroinc/customer-portal/commit/af89a0510d857258977088d9a32a21ed19b1ef57
As you can see https://github.com/oroinc/customer-portal/blob/master/src/Oro/Bundle/CustomerBundle/EventListener/Datagrid/CustomerDatagridListener.php was changed too.

Also I checked https://github.com/oroinc/customer-portal/blob/master/src/Oro/Bundle/CustomerBundle/Security/CustomerUserProvider.php#L195 and in my case the first role was `Buyer` that have `Department` level for `View`. As result I see 45 rows in grid.

Can you please check one more time this problem on your environment, but on last master?

**Comment by xgitxhubx** [comment]
Hi @manowark ,

I have just checked again and it works.

Thank you.
