### ISSUE TITLE
Integrate webpush desktop notification

### ISSUE THREAD

**Issue by AdriwanKenoby** [oroinc/platform#806]
I would recommend to integrate the awesome [https://github.com/bpolaszek/webpush-bundle](https://github.com/bpolaszek/webpush-bundle) which provide ability to send easily push notification to client browser from Symfony app.

**Comment by mbessolov** [comment]
@AdriwanKenoby how is it different from the websocket pub/sub functionality provided by OroSyncBundle ?
https://github.com/oroinc/platform/tree/master/src/Oro/Bundle/SyncBundle

**Comment by AdriwanKenoby** [comment]
Is it possible to send notification directly to the browser's client ? How can i achieve this goal ? When I login into oro their is no pop up "would you like to authorize notifications from Oro". So I figure it s not the same functionality but maybe i am wrong.

**Comment by mbessolov** [comment]
Pub/sub functionality for server to browser notifications is provided by OroSyncBundle. It works via websockets. The messages to the user are displayed in the application UI, not as browser notifications.

The bundle that you are proposing to integrate, uses different delivery mechanism (web push notifications), and displays messages to the user as browser notifications. We have no plans to "replace" websockets with web push protocol any time soon.

If you are interested in displaying the user notifications as browser notifications instead of displaying them in the application UI, it should be relatively easy to achieve with a bit of Javasacript coding. Feel free to open a pull request.
